CREATE TABLE public.black_list
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userId        INTEGER,
    reason        VARCHAR(255),
    description   VARCHAR(255),
    blockTime     TIMESTAMP WITHOUT TIME ZONE,
    blockDuration BIGINT,
    CONSTRAINT pk_black_list PRIMARY KEY (id)
);

CREATE TABLE public.cart
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    productId INTEGER,
    price     DOUBLE PRECISION,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE public.category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE public.orders
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userId INTEGER,
    price  DOUBLE PRECISION,
    cartId INTEGER,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE public.product
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    categoryId  INTEGER,
    name        VARCHAR(255),
    description VARCHAR(255),
    price       DOUBLE PRECISION,
    status      VARCHAR(255),
    image       VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE public.promo_code
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code           VARCHAR(255),
    price          DOUBLE PRECISION,
    discount       DOUBLE PRECISION,
    startFrom      date,
    expirationDate date,
    CONSTRAINT pk_promo_code PRIMARY KEY (id)
);

CREATE TABLE public.promo_code_usage
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userId      INTEGER,
    promoCodeId INTEGER,
    usageDate   date,
    CONSTRAINT pk_promo_code_usage PRIMARY KEY (id)
);

CREATE TABLE public.role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login     VARCHAR(255),
    firstName VARCHAR(255),
    lastName  VARCHAR(255),
    email     VARCHAR(255),
    roleId    INTEGER,
    address   VARCHAR(255),
    password  VARCHAR(255),
    birthday  date,
    CONSTRAINT pk_users PRIMARY KEY (id)
);